language: generic 

# To use docker, we will need super user privilege, and so we are asing for sudo access
sudo: required
# Tell tracis that  we will need docker and it will install a local copy of docker
servives:
  - docker

before_install:
  - docker build -t akshay110495/docker-react -f Dockerfile.dev .

script:
- docker run akshay110495/docker-react npm run test -- --coverage